SELECT `TABLE_SCHEMA`, `TABLE_NAME`, `TABLE_TYPE`, `CREATE_TIME`, `UPDATE_TIME`, `TABLE_COMMENT`
FROM `INFORMATION_SCHEMA`.`TABLES`
WHERE `TABLE_SCHEMA` = '${tableSchema}' AND `TABLE_NAME` = '${tableName}'
