SELECT `CONSTRAINT_SCHEMA`, `CONSTRAINT_NAME`, `UPDATE_RULE`, `DELETE_RULE`, `TABLE_NAME`, `REFERENCED_TABLE_NAME`
FROM `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS`
WHERE `CONSTRAINT_SCHEMA` = '${tableSchema}' AND `TABLE_NAME` = '${tableName}'
