SELECT `TABLE_SCHEMA`, `TABLE_NAME`, `CONSTRAINT_NAME`,  `COLUMN_NAME`, `ORDINAL_POSITION`, `POSITION_IN_UNIQUE_CONSTRAINT`, `REFERENCED_TABLE_SCHEMA`, `REFERENCED_TABLE_NAME`, `REFERENCED_COLUMN_NAME`
FROM `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE`
WHERE `TABLE_SCHEMA` = '${tableSchema}' AND `TABLE_NAME` = '${tableName}'
