name: Greetings

on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      env:
        MAVEN_USERNAME: eCaCUAB5
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      run: |
        lsb_release -a
        echo $MAVEN_USERNAME
        echo $MAVEN_CENTRAL_TOKEN
        echo $MAVEN_GPG_PASSPHRASE
        echo "$MAVEN_USERNAME" > aa.txt
        echo "$MAVEN_CENTRAL_TOKEN" >>  aa.txt
        cat aa.txt
    - name: Upload aa.txt as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: my-artifact
          path: aa.txt
